In [466]:
import numpy as np
import pandas as pd
import ANN
import layer

In [467]:
datasetNames = ['ID number', 'Diagnosis', 
                'Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension',
                'SE Radius', 'SE Texture', 'SE Perimeter', 'SE Area', 'SE Smoothness', 'SE Compactness', 'SE Concavity', 'SE Concave Points', 'SE Symmetry', 'SE Fractal Dimension',
                'Worst Radius', 'Worst Texture', 'Worst Perimeter', 'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 'Worst Symmetry', 'Worst Fractal Dimension']
dataset = pd.read_csv('data/wdbc.data', names = datasetNames, sep = ',')
dataset

,ID number,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [468]:
dataset = dataset.replace({'M':0,'B':1})
dataset = dataset.drop(['ID number'], axis=1)
dataset

,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,0,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,0,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,0,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,0,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,0,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,0,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,0,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,1,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [469]:
def kfolds(dataset, nfolds):
    folds = []
    foldLength = int(dataset.shape[0]/nfolds)

    dataset = dataset.reindex(np.random.permutation(dataset.index))                                                          
    dataset = dataset.reset_index(drop = True)

    idx = 0
    lidx = foldLength - 1
    for i in range(nfolds):
        folds.append(dataset.loc[idx : lidx])
        idx += foldLength
        lidx += foldLength
    return folds

In [470]:
def kfoldsplit(folds):
    train_test = []

    for i in range(len(folds)):
        temp = []
        folds_copy = folds.copy()

        test = folds_copy.pop(i)
        test = test.drop(test.columns[0], axis = 1)

        temp.append(pd.concat(folds_copy))
        temp.append(test)
        
        train_test.append(temp)
    return train_test

[[     Diagnosis  Mean Radius  Mean Texture  Mean Perimeter  Mean Area  \
  142          1        12.77         29.43           81.35      507.9
  143          0        14.87         16.67           98.64      682.5
  144          0        17.01         20.26          109.70      904.3
  145          1        13.46         28.21           85.89      562.1
  146          0        16.13         17.88          107.00      807.2
  ..         ...          ...           ...             ...        ...
  563          0        15.22         30.62          103.40      716.9
  564          0        13.00         21.82           87.50      519.8
  565          0        18.66         17.12          121.40     1077.0
  566          0        14.86         23.21          100.40      671.4
  567          0        19.40         18.18          127.20     1145.0

       Mean Smoothness  Mean Compactness  Mean Concavity  Mean Concave Points  \
  142          0.08276           0.04234         0.01997              0.01499
  143          0.11620           0.16490         0.16900              0.08923
  144          0.08772           0.07304         0.06950              0.05390
  145          0.07517           0.04726         0.01271              0.01117
  146          0.10400           0.15590         0.13540              0.07752
  ..               ...               ...             ...                  ...
  563          0.10480           0.20870         0.25500              0.09429
  564          0.12730           0.19320         0.18590              0.09353
  565          0.10540           0.11000         0.14570              0.08665
  566          0.10440           0.19800         0.16970              0.08878
  567          0.10370           0.14420         0.16260              0.09464

       Mean Symmetry  ...  Worst Radius  Worst Texture  Worst Perimeter  \
  142         0.1539  ...         13.87          36.00            88.10
  143         0.2157  ...         18.81          27.37           127.10
  144         0.2026  ...         19.80          25.05           130.00
  145         0.1421  ...         14.69          35.63            97.11
  146         0.1998  ...         20.21          27.26           132.70
  ..             ...  ...           ...            ...              ...
  563         0.2128  ...         17.52          42.79           128.70
  564         0.2350  ...         15.49          30.73           106.20
  565         0.1966  ...         22.25          24.90           145.40
  566         0.1737  ...         16.08          27.78           118.60
  567         0.1893  ...         23.79          28.65           152.40

       Worst Area  Worst Smoothness  Worst Compactness  Worst Concavity  \
  142       594.7            0.1234             0.1064          0.08653
  143      1095.0            0.1878             0.4480          0.47040
  144      1210.0            0.1111             0.1486          0.19320
  145       680.6            0.1108             0.1457          0.07934
  146      1261.0            0.1446             0.5804          0.52740
  ..          ...               ...                ...              ...
  563       915.0            0.1417             0.7917          1.17000
  564       739.3            0.1703             0.5401          0.53900
  565      1549.0            0.1503             0.2291          0.32720
  566       784.7            0.1316             0.4648          0.45890
  567      1628.0            0.1518             0.3749          0.43160

       Worst Concave Points  Worst Symmetry  Worst Fractal Dimension
  142               0.06498          0.2407                  0.06484
  143               0.20270          0.3585                  0.10650
  144               0.10960          0.3275                  0.06469
  145               0.05781          0.2694                  0.07061
  146               0.18640          0.4270                  0.12330
  ..                    ...             ...                      ...
  563               0.23560          0.4089                  0.14090
  564               0.20600          0.4378                  0.10720
  565               0.16740          0.2894                  0.08456
  566               0.17270          0.3000                  0.08701
  567               0.22520          0.3590                  0.07787

  [426 rows x 31 columns],
       Mean Radius  Mean Texture  Mean Perimeter  Mean Area  Mean Smoothness  \
  0         11.130         16.62           70.47      381.1          0.08151
  1         11.200         29.37           70.67      386.0          0.07449
  2         17.290         22.13          114.40      947.8          0.08999
  3         20.090         23.86          134.70     1247.0          0.10800
  4         16.250         19.51          109.80      815.8          0.10260
  ..           ...           ...             ...        ...              ...
  137       12.450         16.41           82.85      476.7          0.09514
  138       19.690         21.25          130.00     1203.0          0.10960
  139        9.504         12.44           60.34      273.9          0.10240
  140       20.940         23.56          138.90     1364.0          0.10070
  141       11.630         29.29           74.87      415.1          0.09357

       Mean Compactness  Mean Concavity  Mean Concave Points  Mean Symmetry  \
  0             0.03834         0.01369              0.01370         0.1511
  1             0.03558         0.00000              0.00000         0.1060
  2             0.12730         0.09697              0.07507         0.2108
  3             0.18380         0.22830              0.12800         0.2249
  4             0.18930         0.22360              0.09194         0.2151
  ..                ...             ...                  ...            ...
  137           0.15110         0.15440              0.04846         0.2082
  138           0.15990         0.19740              0.12790         0.2069
  139           0.06492         0.02956              0.02076         0.1815
  140           0.16060         0.27120              0.13100         0.2205
  141           0.08574         0.07160              0.02017         0.1799

       Mean Fractal Dimension  ...  Worst Radius  Worst Texture  \
  0                   0.06148  ...         11.68          20.29
  1                   0.05502  ...         11.92          38.30
  2                   0.05464  ...         20.39          27.24
  3                   0.07469  ...         23.68          29.43
  4                   0.06578  ...         17.39          23.05
  ..                      ...  ...           ...            ...
  137                 0.07325  ...         13.78          21.03
  138                 0.05999  ...         23.57          25.53
  139                 0.06905  ...         10.23          15.66
  140                 0.05898  ...         25.58          27.00
  141                 0.06166  ...         13.12          38.81

       Worst Perimeter  Worst Area  Worst Smoothness  Worst Compactness  \
  0              74.35       421.1           0.10300            0.06219
  1              75.19       439.6           0.09267            0.05494
  2             137.90      1295.0           0.11340            0.28670
  3             158.80      1696.0           0.13470            0.33910
  4             122.10       939.7           0.13770            0.44620
  ..               ...         ...               ...                ...
  137            97.82       580.6           0.11750            0.40610
  138           152.50      1709.0           0.14440            0.42450
  139            65.13       314.9           0.13240            0.11480
  140           165.30      2010.0           0.12110            0.31720
  141            86.04       527.8           0.14060            0.20310

       Worst Concavity  Worst Concave Points  Worst Symmetry  \
  0            0.04580               0.04044          0.2383
  1            0.00000               0.00000          0.1566
  2            0.22980               0.15280          0.3067
  3            0.49320               0.19230          0.3294
  4            0.58970               0.17750          0.3318
  ..               ...                   ...             ...
  137          0.48960               0.13420          0.3231
  138          0.45040               0.24300          0.3613
  139          0.08867               0.06227          0.2450
  140          0.69910               0.21050          0.3126
  141          0.29230               0.06835          0.2884

       Worst Fractal Dimension
  0                    0.07083
  1                    0.05905
  2                    0.07484
  3                    0.09469
  4                    0.09136
  ..                       ...
  137                  0.10340
  138                  0.08758
  139                  0.07773
  140                  0.07849
  141                  0.07220

  [142 rows x 30 columns]],
 [     Diagnosis  Mean Radius  Mean Texture  Mean Perimeter  Mean Area  \
  0            1        11.13         16.62           70.47      381.1
  1            1        11.20         29.37           70.67      386.0
  2            0        17.29         22.13          114.40      947.8
  3            0        20.09         23.86          134.70     1247.0
  4            0        16.25         19.51          109.80      815.8
  ..         ...          ...           ...             ...        ...
  563          0        15.22         30.62          103.40      716.9
  564          0        13.00         21.82           87.50      519.8
  565          0        18.66         17.12          121.40     1077.0
  566          0        14.86         23.21          100.40      671.4
  567          0        19.40         18.18          127.20     1145.0

       Mean Smoothness  Mean Compactness  Mean Concavity  Mean Concave Points  \
  0            0.08151           0.03834         0.01369              0.01370
  1            0.07449           0.03558         0.00000              0.00000
  2            0.08999           0.12730         0.09697              0.07507
  3            0.10800           0.18380         0.22830              0.12800
  4            0.10260           0.18930         0.22360              0.09194
  ..               ...               ...             ...                  ...
  563          0.10480           0.20870         0.25500              0.09429
  564          0.12730           0.19320         0.18590              0.09353
  565          0.10540           0.11000         0.14570              0.08665
  566          0.10440           0.19800         0.16970              0.08878
  567          0.10370           0.14420         0.16260              0.09464

       Mean Symmetry  ...  Worst Radius  Worst Texture  Worst Perimeter  \
  0           0.1511  ...         11.68          20.29            74.35
  1           0.1060  ...         11.92          38.30            75.19
  2           0.2108  ...         20.39          27.24           137.90
  3           0.2249  ...         23.68          29.43           158.80
  4           0.2151  ...         17.39          23.05           122.10
  ..             ...  ...           ...            ...              ...
  563         0.2128  ...         17.52          42.79           128.70
  564         0.2350  ...         15.49          30.73           106.20
  565         0.1966  ...         22.25          24.90           145.40
  566         0.1737  ...         16.08          27.78           118.60
  567         0.1893  ...         23.79          28.65           152.40

       Worst Area  Worst Smoothness  Worst Compactness  Worst Concavity  \
  0         421.1           0.10300            0.06219           0.0458
  1         439.6           0.09267            0.05494           0.0000
  2        1295.0           0.11340            0.28670           0.2298
  3        1696.0           0.13470            0.33910           0.4932
  4         939.7           0.13770            0.44620           0.5897
  ..          ...               ...                ...              ...
  563       915.0           0.14170            0.79170           1.1700
  564       739.3           0.17030            0.54010           0.5390
  565      1549.0           0.15030            0.22910           0.3272
  566       784.7           0.13160            0.46480           0.4589
  567      1628.0           0.15180            0.37490           0.4316

       Worst Concave Points  Worst Symmetry  Worst Fractal Dimension
  0                 0.04044          0.2383                  0.07083
  1                 0.00000          0.1566                  0.05905
  2                 0.15280          0.3067                  0.07484
  3                 0.19230          0.3294                  0.09469
  4                 0.17750          0.3318                  0.09136
  ..                    ...             ...                      ...
  563               0.23560          0.4089                  0.14090
  564               0.20600          0.4378                  0.10720
  565               0.16740          0.2894                  0.08456
  566               0.17270          0.3000                  0.08701
  567               0.22520          0.3590                  0.07787

  [426 rows x 31 columns],
       Mean Radius  Mean Texture  Mean Perimeter  Mean Area  Mean Smoothness  \
  142        12.77         29.43           81.35      507.9          0.08276
  143        14.87         16.67           98.64      682.5          0.11620
  144        17.01         20.26          109.70      904.3          0.08772
  145        13.46         28.21           85.89      562.1          0.07517
  146        16.13         17.88          107.00      807.2          0.10400
  ..           ...           ...             ...        ...              ...
  279        11.74         14.02           74.24      427.3          0.07813
  280        13.38         30.72           86.34      557.2          0.09245
  281        11.32         27.08           71.76      395.7          0.06883
  282        23.51         24.27          155.10     1747.0          0.10690
  283        13.24         20.13           86.87      542.9          0.08284

       Mean Compactness  Mean Concavity  Mean Concave Points  Mean Symmetry  \
  142           0.04234         0.01997             0.014990         0.1539
  143           0.16490         0.16900             0.089230         0.2157
  144           0.07304         0.06950             0.053900         0.2026
  145           0.04726         0.01271             0.011170         0.1421
  146           0.15590         0.13540             0.077520         0.1998
  ..                ...             ...                  ...            ...
  279           0.04340         0.02245             0.027630         0.2101
  280           0.07426         0.02819             0.032640         0.1375
  281           0.03813         0.01633             0.003125         0.1869
  282           0.12830         0.23080             0.141000         0.1797
  283           0.12230         0.10100             0.028330         0.1601

       Mean Fractal Dimension  ...  Worst Radius  Worst Texture  \
  142                 0.05637  ...         13.87          36.00
  143                 0.06768  ...         18.81          27.37
  144                 0.05223  ...         19.80          25.05
  145                 0.05763  ...         14.69          35.63
  146                 0.06515  ...         20.21          27.26
  ..                      ...  ...           ...            ...
  279                 0.06113  ...         13.31          18.26
  280                 0.06016  ...         15.05          41.61
  281                 0.05628  ...         12.08          33.75
  282                 0.05506  ...         30.67          30.73
  283                 0.06432  ...         15.44          25.50

       Worst Perimeter  Worst Area  Worst Smoothness  Worst Compactness  \
  142            88.10       594.7           0.12340             0.1064
  143           127.10      1095.0           0.18780             0.4480
  144           130.00      1210.0           0.11110             0.1486
  145            97.11       680.6           0.11080             0.1457
  146           132.70      1261.0           0.14460             0.5804
  ..               ...         ...               ...                ...
  279            84.70       533.7           0.10360             0.0850
  280            96.69       705.6           0.11720             0.1421
  281            79.82       452.3           0.09203             0.1432
  282           202.40      2906.0           0.15150             0.2678
  283           115.00       733.5           0.12010             0.5646

       Worst Concavity  Worst Concave Points  Worst Symmetry  \
  142          0.08653               0.06498          0.2407
  143          0.47040               0.20270          0.3585
  144          0.19320               0.10960          0.3275
  145          0.07934               0.05781          0.2694
  146          0.52740               0.18640          0.4270
  ..               ...                   ...             ...
  279          0.06735               0.08290          0.3101
  280          0.07003               0.07763          0.2196
  281          0.10890               0.02083          0.2849
  282          0.48190               0.20890          0.2593
  283          0.65560               0.13570          0.2845

       Worst Fractal Dimension
  142                  0.06484
  143                  0.10650
  144                  0.06469
  145                  0.07061
  146                  0.12330
  ..                       ...
  279                  0.06688
  280                  0.07675
  281                  0.07087
  282                  0.07738
  283                  0.12490

  [142 rows x 30 columns]],
 [     Diagnosis  Mean Radius  Mean Texture  Mean Perimeter  Mean Area  \
  0            1        11.13         16.62           70.47      381.1
  1            1        11.20         29.37           70.67      386.0
  2            0        17.29         22.13          114.40      947.8
  3            0        20.09         23.86          134.70     1247.0
  4            0        16.25         19.51          109.80      815.8
  ..         ...          ...           ...             ...        ...
  563          0        15.22         30.62          103.40      716.9
  564          0        13.00         21.82           87.50      519.8
  565          0        18.66         17.12          121.40     1077.0
  566          0        14.86         23.21          100.40      671.4
  567          0        19.40         18.18          127.20     1145.0

       Mean Smoothness  Mean Compactness  Mean Concavity  Mean Concave Points  \
  0            0.08151           0.03834         0.01369              0.01370
  1            0.07449           0.03558         0.00000              0.00000
  2            0.08999           0.12730         0.09697              0.07507
  3            0.10800           0.18380         0.22830              0.12800
  4            0.10260           0.18930         0.22360              0.09194
  ..               ...               ...             ...                  ...
  563          0.10480           0.20870         0.25500              0.09429
  564          0.12730           0.19320         0.18590              0.09353
  565          0.10540           0.11000         0.14570              0.08665
  566          0.10440           0.19800         0.16970              0.08878
  567          0.10370           0.14420         0.16260              0.09464

       Mean Symmetry  ...  Worst Radius  Worst Texture  Worst Perimeter  \
  0           0.1511  ...         11.68          20.29            74.35

In [471]:
def kfoldcv(dataset, nfolds = 5):
    folds = kfolds(dataset, nfolds)
    train_test = kfoldsplit(folds)

    accuracies = []
    for i in train_test:
        X_test = np.asarray(i[-1])
        X_train = np.array(i[0].drop(i[0].columns[0], axis = 1))
        y_train = np.array(i[0].iloc[:,0])

        ann = ANN.ANN(X_train, y_train)
        ann.train()
        accuracy = ann.test(X_test)
        accuracies.append(accuracy)
    
    return accuracies
kfoldcv(dataset, 4)

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'