In [25]:
import numpy as np
import pandas as pd
import NeuralNet
import layer

In [26]:
datasetNames = ['ID number', 'Diagnosis', 
                'Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension',
                'SE Radius', 'SE Texture', 'SE Perimeter', 'SE Area', 'SE Smoothness', 'SE Compactness', 'SE Concavity', 'SE Concave Points', 'SE Symmetry', 'SE Fractal Dimension',
                'Worst Radius', 'Worst Texture', 'Worst Perimeter', 'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 'Worst Symmetry', 'Worst Fractal Dimension']
dataset = pd.read_csv('data/wdbc.data', names = datasetNames, sep = ',')
dataset = dataset.drop(columns=['ID number'])
dataset.head()

,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [27]:
dataset = dataset.replace({'M':0,'B':1})                                                     
dataset.head()

,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,0,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,0,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,0,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,0,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [28]:
def kfolds(dataset, nfolds):
    folds = []
    foldLength = int(dataset.shape[0]/nfolds)

    dataset = dataset.reindex(np.random.permutation(dataset.index))                                                          
    dataset = dataset.reset_index(drop = True)
    
    idx = 0
    lidx = foldLength - 1
    for i in range(nfolds):
        folds.append(dataset.loc[idx : lidx])
        idx += foldLength
        lidx += foldLength
    return folds

In [29]:
def kfoldsplit(folds):
    train_test = []

    for i in range(len(folds)):
        temp = []
        folds_copy = folds.copy()

        test = folds_copy.pop(i)

        temp.append(pd.concat(folds_copy))
        temp.append(test)
        
        train_test.append(temp)
    return train_test

In [30]:
def kfoldcv(dataset, nfolds = 5):
    folds = kfolds(dataset, nfolds)
    train_test = kfoldsplit(folds)

    accuracies = []
    for i in train_test:
        X_test = np.asarray(i[-1].drop(i[0].columns[0], axis = 1)).T
        y_test = np.array(i[-1].iloc[:,0]).T

        X_mean = np.mean(X_test,axis=1,keepdims=True) #Find the mean of each feature
        X_max = np.max(X_test,axis=1,keepdims=True) #Find the maximum of each feature
        X_test = (X_test-X_mean)/(X_max)

        print("testing data", X_test, y_test)

        X_train = np.array(i[0].drop(i[0].columns[0], axis = 1)).T
        y_train = np.array(i[0].iloc[:,0]).T

        X_mean = np.mean(X_train,axis=1,keepdims=True) #Find the mean of each feature
        X_max = np.max(X_train,axis=1,keepdims=True) #Find the maximum of each feature
        X_normalized = (X_train-X_mean)/(X_max) #Normalizing our dataset by subtracting the mean and dividing by the max

        X_train = X_normalized
        print("training data", X_train, y_train)

        ann = NeuralNet.ANN(0.1, 2, X_train, y_train)
        activations = [2,2]
        ann.setLayers(activations, 2, 1)

        ann.train_sgd()
        accuracy = ann.test(X_test, y_test)
        accuracies.append(accuracy)
    
    return accuracies
kfoldcv(dataset, 4)

testing data [[ 0.00343911  0.08122167  0.09024616 ...  0.05543739  0.01246361
  -0.03652651]
 [-0.07940396  0.06877705 -0.14269884 ...  0.11166377 -0.06313658
  -0.15926199]
 [-0.00284653  0.09616727  0.09025011 ...  0.09090758  0.00458279
  -0.03933569]
 ...
 [-0.14082108  0.42783978  0.12673043 ...  0.56294279 -0.17113011
  -0.08440269]
 [ 0.12809985  0.05106566 -0.01633925 ...  0.0180854  -0.02693145
  -0.05461561]
 [-0.0451852   0.15260839 -0.09002506 ...  0.22876497 -0.04539873
  -0.00589695]] [1 0 1 1 0 1 1 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1
 0 1 1 1 0 1 1 0 0 0 1 1 1 0 1 0 1 0 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 0
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1]
training data [[ 0.06643226  0.00809003  0.46664571 ...  0.27418751 -0.07942331
  -0.16302345]
 [-0.08668354 -0.13989128  0.17299059 ...  0.06173805 -0.15363874
  -0.03194831]
 [ 0.06937286  0.00337816  0.49695907 ...  0.28634899 -0.08166162
  -0.1723778 ]
 ...
 [ 0.02527055 -0.03727241  0.4974355  ...  0.43111247 -0.15057137
  -0.40462636]
 [ 0.03252578 -0.04987856 -0.04460589 ... -0.02954111 -0.0235152
  -0.15488007]
 [ 0.02614209 -0.0292796  -0.04773743 ...  0.00753968 -0.01761695
  -0.08956875]] [1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 0 0 1 1 1
 0 0 1 0 1 0 0 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 1
 0 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 0 1 1
 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 0
 1 1 1 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 0 0 0 1 1
 1 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1
 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0
 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 1
 0 1 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1 0 0 1
 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 1
 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 0 1
 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1]
the activations are [2, 2]
the variable argument is  (2, 1)
number of hidden layers 1

input to the network is [[ 0.06643226  0.00809003  0.46664571 ...  0.27418751 -0.07942331
  -0.16302345]
 [-0.08668354 -0.13989128  0.17299059 ...  0.06173805 -0.15363874
  -0.03194831]
 [ 0.06937286  0.00337816  0.49695907 ...  0.28634899 -0.08166162
  -0.1723778 ]
 ...
 [ 0.02527055 -0.03727241  0.4974355  ...  0.43111247 -0.15057137
  -0.40462636]
 [ 0.03252578 -0.04987856 -0.04460589 ... -0.02954111 -0.0235152
  -0.15488007]
 [ 0.02614209 -0.0292796  -0.04773743 ...  0.00753968 -0.01761695
  -0.08956875]]
the output is [1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 0 0 1 1 1
 0 0 1 0 1 0 0 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 1
 0 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 0 1 1
 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 0
 1 1 1 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 0 0 0 1 1
 1 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1
 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0
 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 1
 0 1 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1 0 0 1
 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 1
 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 0 1
 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1]
adding input layer
added 1 hidden layer
added 1 output layer
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>
weights [[-0.21390359  0.24663124 -0.23928792  0.11346495  0.33123924 -0.20647172
  -0.44714639 -0.15301438  0.13877799 -0.03068836  0.40886816 -0.22940806
   0.19928915  0.05224117  0.07618134  0.1619303   0.33733537 -0.38624067
   0.14261325 -0.26570828 -0.452307    0.21563612 -0.47207766 -0.04478108
   0.43381751  0.47139284  0.37683253  0.13349185  0.36029784 -0.37641055]
 [ 0.08262313 -0.36224443 -0.33589287  0.47330281 -0.07384242 -0.3149799
  -0.41452678  0.24755075  0.07425323  0.21237074 -0.28089863  0.38695922
  -0.19542955 -0.03147533 -0.35628281 -0.03901093 -0.25877753  0.22668012
  -0.42096286 -0.21599378  0.47911661 -0.28365702  0.40300758 -0.36649083
  -0.24914084 -0.08770836 -0.10364272 -0.47549373  0.33919031 -0.02542893]]
layers in for prog <layer.Layer object at 0x000001CB8907C2E0>
weights [[-0.41470342  0.21790239]]
my error function <function mse at 0x000001CB89066B00>
the error was (1, 426) but the error should be
dimensions <layer.Layer object at 0x000001CB8907C2E0> (1, 2) (1, 2) ()
dimensions <layer.Layer object at 0x000001CB8907C190> (2, 30) (2, 30) ()
Iteration:  0
HERE
A2 [[0.13076124 0.12382902 0.14999828 0.09652539 0.         0.00378874
  0.         0.05347444 0.10190092 0.03029008 0.04036642 0.05456602
  0.05066547 0.05790676 0.         0.         0.         0.21224791
  0.07477773 0.         0.02735091 0.08334176 0.02868941 0.11426295
  0.19973845 0.08402444 0.14350547 0.04623776 0.         0.15913109
  0.04957714 0.13165889 0.06190918 0.13777161 0.05469363 0.13027664
  0.07956234 0.21224791 0.15196458 0.17929283 0.         0.
  0.11276023 0.08218536 0.         0.02279204 0.07655633 0.03020244
  0.00965298 0.11661554 0.11969114 0.12136359 0.03735752 0.
  0.04397741 0.0975993  0.03527847 0.08305023 0.04918674 0.04188641
  0.02789701 0.07113864 0.05161184 0.10122924 0.03851253 0.14686047
  0.2010441  0.03780111 0.         0.02215709 0.         0.05711482
  0.         0.14690659 0.08961512 0.10120372 0.00750529 0.
  0.         0.03881759 0.04723136 0.07383232 0.13272947 0.07205434
  0.         0.06126069 0.         0.         0.09458467 0.05076735
  0.00540382 0.09886335 0.01775465 0.01983591 0.04171216 0.06311919
  0.         0.0641823  0.         0.         0.11358743 0.03653672
  0.         0.         0.06883871 0.02458721 0.00997621 0.03653355
  0.03299893 0.00610343 0.18272452 0.         0.         0.02693254
  0.         0.14771318 0.13948946 0.05653023 0.12789054 0.17289213
  0.09839085 0.18714436 0.03923598 0.07560247 0.05777711 0.09360802
  0.0979309  0.00603402 0.0438388  0.06738221 0.         0.07035123
  0.03291677 0.05121623 0.         0.         0.18219227 0.10380922
  0.         0.16598858 0.08434538 0.02323593 0.         0.12400189
  0.06699943 0.08977815 0.12536076 0.15169812 0.044306   0.1697862
  0.04708571 0.         0.         0.09799269 0.08076782 0.05354281
  0.         0.13773264 0.04519105 0.18158211 0.08077416 0.
  0.         0.04077356 0.15012358 0.00305499 0.         0.03018499
  0.         0.11759509 0.         0.03639459 0.07031631 0.
  0.02068412 0.06804497 0.07976129 0.27134801 0.02006366 0.
  0.17983477 0.12041414 0.14286182 0.10015819 0.         0.01095848
  0.04148591 0.03648506 0.15223177 0.04422269 0.05749837 0.01970817
  0.15720298 0.0448908  0.11952131 0.         0.13216281 0.
  0.         0.         0.1823779  0.0659652  0.03267435 0.03440187
  0.17240639 0.05612794 0.16191988 0.         0.17649906 0.01535693
  0.12113782 0.10423087 0.06639353 0.00615997 0.         0.0573281
  0.         0.11248832 0.         0.18482105 0.         0.09693334
  0.18528898 0.         0.         0.03078067 0.15287692 0.
  0.06160073 0.         0.08568215 0.18929563 0.12355091 0.21221731
  0.         0.06391299 0.03677796 0.         0.01335664 0.06555353
  0.16638917 0.0356928  0.         0.01495443 0.         0.06069692
  0.16696548 0.1440281  0.22221053 0.         0.         0.13405128
  0.07633442 0.0285372  0.07385197 0.11073196 0.11330931 0.21224791
  0.12623535 0.2107559  0.1798542  0.         0.00054508 0.04059001
  0.04106165 0.07338612 0.0270522  0.05438948 0.10803335 0.04978333
  0.         0.06748825 0.05328153 0.09166673 0.         0.
  0.09620619 0.11379301 0.05384736 0.         0.01535844 0.11423024
  0.         0.00192315 0.15266034 0.08350746 0.         0.03134277
  0.12693651 0.13958457 0.         0.00442076 0.         0.06115556
  0.02832294 0.12663035 0.         0.01587563 0.08876987 0.22700606
  0.05326837 0.         0.0192904  0.         0.03153748 0.
  0.10534402 0.10311273 0.09141392 0.09898921 0.06764254 0.01267247
  0.0290898  0.13114903 0.00805229 0.02073131 0.08957909 0.10236331
  0.         0.         0.00263874 0.         0.02205331 0.06628488
  0.12272519 0.03912218 0.00930156 0.05498169 0.0063086  0.
  0.03742828 0.05461688 0.02753872 0.04879024 0.06983638 0.
  0.         0.         0.21224791 0.02796271 0.02451768 0.04116827
  0.11759873 0.         0.10627805 0.         0.19471854 0.12596967
  0.01428238 0.08354462 0.00414498 0.         0.05938357 0.05397129
  0.         0.07507565 0.15775988 0.03020969 0.02053323 0.09276787
  0.10831902 0.15510618 0.04150004 0.07662355 0.10110647 0.15137282
  0.05449916 0.06278657 0.09535598 0.10401845 0.0522011  0.14038284
  0.07256029 0.1434779  0.05672068 0.14595312 0.06636506 0.03693764
  0.08709037 0.13801316 0.13079904 0.         0.1793478  0.06859879
  0.14335047 0.12221426 0.02666233 0.09884551 0.15846571 0.
  0.02298373 0.1158854  0.102797   0.         0.04206123 0.
  0.04090107 0.04457411 0.07753539 0.07904201 0.         0.0224902
  0.         0.12693363 0.         0.14508134 0.         0.12658646
  0.07562703 0.1214644  0.15251556 0.         0.         0.
  0.09354842 0.02271494 0.15472338 0.06357135 0.         0.04151705
  0.12519609 0.02138743 0.         0.18682648 0.02949393 0.2269525 ]]
PRED [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
169
Accuracy  0.3967136150234742
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>
weights [[-0.21185313  0.24755372 -0.23714862  0.11569761  0.33191587 -0.20454965
  -0.44439264 -0.14980498  0.1393691  -0.03077088  0.4100718  -0.22942673
   0.20042252  0.05327443  0.07597977  0.16275405  0.33772477 -0.38523246
   0.14253659 -0.26558373 -0.45002287  0.2167683  -0.46977586 -0.04262315
   0.43461226  0.47319143  0.37907298  0.13723032  0.36104123 -0.37589295]
 [ 0.08185933 -0.36273081 -0.33670785  0.47246296 -0.07421419 -0.31605449
  -0.41594319  0.2461256   0.07394086  0.21220605 -0.2814077   0.38683608
  -0.19592753 -0.03188589 -0.35639569 -0.03976884 -0.25917781  0.22599457
  -0.42105081 -0.21634083  0.47824669 -0.28422379  0.40211033 -0.36731704
  -0.24958906 -0.08870649 -0.10487907 -0.47722424  0.33884081 -0.0258458 ]]
layers in for prog <layer.Layer object at 0x000001CB8907C2E0>
weights [[-0.38866878  0.22607753]]
my error function <function mse at 0x000001CB89066B00>
the error was (1, 426) but the error should be
dimensions <layer.Layer object at 0x000001CB8907C2E0> (1, 2) (1, 2) ()
dimensions <layer.Layer object at 0x000001CB8907C190> (2, 30) (2, 30) ()
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>
weights [[-0.20993196  0.24839712 -0.23514689  0.11778622  0.33252352 -0.20279696
  -0.44185866 -0.14683234  0.13989621 -0.03087362  0.41119284 -0.22945682
   0.20147577  0.05423876  0.0757764   0.16348881  0.33807366 -0.38430409
   0.14244402 -0.26548554 -0.4478883   0.21779959 -0.46762827 -0.0406079
   0.43531921  0.47481819  0.38111396  0.14067889  0.36170267 -0.37544553]
 [ 0.08113414 -0.36320622 -0.33748088  0.4716646  -0.07455101 -0.31706534
  -0.4172796   0.24477672  0.07364611  0.21205072 -0.28188886  0.38672247
  -0.19639791 -0.03227476 -0.35650152 -0.04048245 -0.25955383  0.225349
  -0.4211292  -0.21667673  0.47741994 -0.28477631  0.4012584  -0.36810302
  -0.25000861 -0.0896494  -0.10605014 -0.47886999  0.33850915 -0.02624824]]
layers in for prog <layer.Layer object at 0x000001CB8907C2E0>
weights [[-0.36588505  0.23311397]]
my error function <function mse at 0x000001CB89066B00>
the error was (1, 426) but the error should be
dimensions <layer.Layer object at 0x000001CB8907C2E0> (1, 2) (1, 2) ()
dimensions <layer.Layer object at 0x000001CB8907C190> (2, 30) (2, 30) ()
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>
weights [[-0.20814072  0.24918378 -0.2332811   0.11973151  0.33308588 -0.20117355
  -0.4395067  -0.14406679  0.14038447 -0.03097693  0.41223702 -0.22948992
   0.20245576  0.05513682  0.07558504  0.16415957  0.33839133 -0.38344574
   0.14235134 -0.26540251 -0.44589737  0.21876093 -0.46562581 -0.03872977
   0.43597596  0.47632496  0.38300667  0.1438901   0.3623163  -0.3750366 ]
 [ 0.08043067 -0.36366559 -0.33822916  0.47089146 -0.07486967 -0.31802416
  -0.41855108  0.24349293  0.07336414  0.21190885 -0.2823478   0.38662296
  -0.19684495 -0.03264714 -0.35659293 -0.04115282 -0.25991089  0.22473656
  -0.42119091 -0.21699028  0.47661921 -0.28530854  0.40043557 -0.36886333
  -0.25040665 -0.09054423 -0.10717172 -0.48044379  0.33819382 -0.02662779]]
layers in for prog <layer.Layer object at 0x000001CB8907C2E0>
weights [[-0.34617106  0.23928428]]
my error function <function mse at 0x000001CB89066B00>
the error was (1, 426) but the error should be
dimensions <layer.Layer object at 0x000001CB8907C2E0> (1, 2) (1, 2) ()
dimensions <layer.Layer object at 0x000001CB8907C190> (2, 30) (2, 30) ()
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>
weights [[-0.20646373  0.2499245  -0.23153438  0.12155141  0.3336144  -0.19965484
  -0.43730516 -0.14147675  0.14084375 -0.03107581  0.41321487 -0.22952376
   0.20337266  0.05597745  0.07540637  0.16478187  0.33868573 -0.38264547
   0.14226158 -0.26532932 -0.44403142  0.2196669  -0.4637491  -0.03697061
   0.43659615  0.47773797  0.38478189  0.14690221  0.36289479 -0.37465383]
 [ 0.07975782 -0.36410601 -0.33894419  0.47015218 -0.07516563 -0.31893251
  -0.41975925  0.24227266  0.07309535  0.211778   -0.28278123  0.38653294
  -0.19726667 -0.03300061 -0.35666789 -0.04178683 -0.26025161  0.22415693
  -0.42123733 -0.21728189  0.47585416 -0.28582202  0.39964992 -0.36958947
  -0.25078051 -0.09139825 -0.1082497  -0.48194745  0.3378945  -0.02698609]]
layers in for prog <layer.Layer object at 0x000001CB8907C2E0>
weights [[-0.32905689  0.24480393]]
my error function <function mse at 0x000001CB89066B00>
the error was (1, 426) but the error should be
dimensions <layer.Layer object at 0x000001CB8907C2E0> (1, 2) (1, 2) ()
dimensions <layer.Layer object at 0x000001CB8907C190> (2, 30) (2, 30) ()
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>
weights [[-0.2048743   0.25062768 -0.22987873  0.12327726  0.33411708 -0.19821235
  -0.43521854 -0.13902102  0.14128163 -0.03116677  0.41414177 -0.22955937
   0.20424097  0.05677406  0.07523692  0.16537016  0.33896351 -0.38189061
   0.14217715 -0.2652609  -0.44226196  0.22052699 -0.46196914 -0.03530174
   0.43718716  0.4790814   0.38646688  0.14976067  0.36344794 -0.37428733]
 [ 0.07910024 -0.36453048 -0.33964142  0.46943046 -0.07544308 -0.31979672
  -0.42091455  0.24109997  0.07284115  0.21166095 -0.28320054  0.38644987
  -0.19767322 -0.03334311 -0.35673221 -0.04238663 -0.26057554  0.22360373
  -0.42127603 -0.21755576  0.47510809 -0.28631702  0.39888578 -0.37029708
  -0.25113298 -0.09221127 -0.10928069 -0.48339275  0.33760868 -0.02732385]]
layers in for prog <layer.Layer object at 0x000001CB8907C2E0>
weights [[-0.31414509  0.24982499]]
my error function <function mse at 0x000001CB89066B00>
the error was (1, 426) but the error should be
dimensions <layer.Layer object at 0x000001CB8907C2E0> (1, 2) (1, 2) ()
dimensions <layer.Layer object at 0x000001CB8907C190> (2, 30) (2, 30) ()
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>
weights [[-0.20336943  0.25129682 -0.22831107  0.12491052  0.33459613 -0.19684327
  -0.43323931 -0.13669311  0.14169945 -0.03125211  0.41501976 -0.22959474
   0.20506279  0.05752826  0.07507689  0.1659279   0.33922667 -0.3811768
   0.14209813 -0.26519733 -0.44058501  0.22134652 -0.46028226 -0.03372088
   0.43775235  0.48036062  0.38806976  0.15247503  0.36397816 -0.3739366 ]
 [ 0.07846125 -0.3649365  -0.34031786  0.46873015 -0.07570326 -0.32062036
  -0.42201848  0.23997638  0.07259988  0.2115549  -0.28360389  0.38637894
  -0.19806333 -0.03367306 -0.35678707 -0.04295486 -0.26088356  0.22307728
  -0.42130761 -0.21781392  0.47438359 -0.28679112  0.39814511 -0.37098351
  -0.25146795 -0.09298853 -0.11026878 -0.48478189  0.33733341 -0.02764458]]
layers in for prog <layer.Layer object at 0x000001CB8907C2E0>
weights [[-0.30109286  0.25446068]]
my error function <function mse at 0x000001CB89066B00>
the error was (1, 426) but the error should be
dimensions <layer.Layer object at 0x000001CB8907C2E0> (1, 2) (1, 2) ()
dimensions <layer.Layer object at 0x000001CB8907C190> (2, 30) (2, 30) ()
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>
weights [[-0.2019378   0.25193615 -0.22681965  0.12646363  0.33505437 -0.1955383
  -0.43135367 -0.13447632  0.14209956 -0.03133278  0.41585532 -0.22962987
   0.20584432  0.0582457   0.07492486  0.16645883  0.33947699 -0.38049867
   0.14202367 -0.26513806 -0.43898833  0.22213044 -0.45867614 -0.03221632
   0.43829463  0.48158345  0.38960067  0.15506371  0.36448797 -0.37359996]
 [ 0.07783846 -0.3653301  -0.34097609  0.46804812 -0.0759478  -0.3214068
  -0.423077    0.23889622  0.07237063  0.21145877 -0.28399506  0.38631151
  -0.19844081 -0.03399325 -0.35683419 -0.04349579 -0.26117795  0.22257319
  -0.42133458 -0.21805808  0.47367831 -0.28725112  0.39742519 -0.37165124
  -0.25178471 -0.09373197 -0.11121679 -0.48611842  0.33706823 -0.02794863]]
layers in for prog <layer.Layer object at 0x000001CB8907C2E0>
weights [[-0.28962801  0.25879413]]
my error function <function mse at 0x000001CB89066B00>
the error was (1, 426) but the error should be
dimensions <layer.Layer object at 0x000001CB8907C2E0> (1, 2) (1, 2) ()
dimensions <layer.Layer object at 0x000001CB8907C190> (2, 30) (2, 30) ()
our layers are [<layer.Layer object at 0x000001CB8907C190>, <layer.Layer object at 0x000001CB8907C2E0>, <layer.Layer object at 0x000001CB8907D390>]
layers in for prog <layer.Layer object at 0x000001CB8907C190>

[0.9507042253521126,
 0.9436619718309859,
 0.9436619718309859,
 0.9436619718309859]