In [83]:
# importing all the libraries required here
import pandas as pd
#import matplotlib.pyplot as plt
import numpy as np

In [88]:
# reading the dataset
datasetNames = ['ID number', 'Diagnosis', 
                'Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension',
                'SE Radius', 'SE Texture', 'SE Perimeter', 'SE Area', 'SE Smoothness', 'SE Compactness', 'SE Concavity', 'SE Concave Points', 'SE Symmetry', 'SE Fractal Dimension',
                'Worst Radius', 'Worst Texture', 'Worst Perimeter', 'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 'Worst Symmetry', 'Worst Fractal Dimension']
dataset = pd.read_csv('data/wdbc.data', names = datasetNames, sep = ',')
dataset.head()

,ID number,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [85]:
dataset = dataset.drop(columns=['ID number'])

m , n = dataset.shape  # m = no. of samples, n = no. of features + target class
m , n

,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [86]:
# change to numpy array 
dataset = np.array(dataset)

# shuffle each row of the data before sending to train network
np.random.shuffle(dataset)

dataset = dataset.T #each column now represents a training set

#sanity check
print(dataset)

[['B' 'M' 'M' ... 'B' 'B' 'B']
 [9.029 17.35 18.31 ... 14.47 11.15 8.95]
 [17.33 23.06 18.58 ... 24.99 13.08 15.76]
 ...
 [0.175 0.08235 0.1571 ... 0.1205 0.05506 0.03846]
 [0.4228 0.2452 0.3206 ... 0.3187 0.2859 0.1652]
 [0.1175 0.06515 0.06938 ... 0.1023 0.06772 0.07722]]

In [89]:
print(dataset.shape)

#seperate training and test sets
X_train = dataset[1:,:400] #train network on 400 samples
Y_train = dataset[0,:400]

X_test = dataset[1:,400:m] #test network on the remaining samples
Y_test = dataset[0,400:m]


print(Y_train)
print(X_train)

InvalidIndexError: (slice(1, None, None), slice(None, 400, None))

In [ ]:
# Initialise ANN
import ANN
import layer

# categorizing data into numericals, 0 = M, 1 = B
Y_train = pd.factorize(Y_train)[0]

# testing one hot encoder
Y_train = ANN.one_hot_encode(Y_train, 2)

In [ ]:
"""REMOVE BEFORE SUBMISSION"""
import importlib
importlib.reload(ANN)
importlib.reload(layer)

# initialise with learning rate, choice of loss funciton, input vector, output vector
ann = ANN.ANN(0.1,1,X_train,Y_train)
activations = [1,1,3] # 1-tanh, 2-relu, 3-sigmoid - activations of each layer
ann.setLayers(activations, 7, 2) # variable arguments represent the number of nodes in each non-input layer 


ann.train()
"""
i = 0
for l in ann.layers:
    print("\nProperties of layer", i, ":")
    l.get_properties()
    i += 1
"""

the activations are [1, 1, 3]
the variable argument is  (7, 2)
number of hidden layers 1

adding input layer
added 1 hidden layer
added 1 output layer
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward
propogating forward

'\ni = 0\nfor l in ann.layers:\n    print("\nProperties of layer", i, ":")\n    l.get_properties()\n    i += 1\n'

In [ ]:
importlib.reload(ANN)
importlib.reload(layer)

#for first 2 columns
#print("the output from the network is", ann.test(np.array(X_train)[:,:2]))
print("the output from the network is", ann.test(np.array(X_train)[:,:1].T))
print(Y_train[0])

test input  [[17.99 10.38 122.8 1001.0 0.1184 0.2776 0.3001 0.1471 0.2419 0.07871
  1.095 0.9053 8.589 153.4 0.006399 0.04904 0.05373 0.01587 0.03003
  0.006193 25.38 17.33 184.6 2019.0 0.1622 0.6656 0.7119 0.2654 0.4601
  0.1189]]
the output from the network is [array([[0., 1.]], dtype=float32)]
[1. 0.]